### ISSUE TITLE
Additional languages

### ISSUE THREAD

**Issue by smiller171** [egoist/vue-prism-component#1]
How do I use this and add languages that are not included?

**Comment by atilacamurca** [comment]
According to this line <https://github.com/egoist/vue-prism-component/blob/master/src/index.js#L17>,
the languages are loaded with `Prism.languages` object.

If you are extending Prism following the example from <http://prismjs.com/extending.html> you know that is just a matter of create a new object and pass to `Prism.languages`, like the following:

```js
Prism.languages.css = {
	'comment': /\/\*[\s\S]*?\*\//,
	'atrule': {
		pattern: /@[\w-]+?.*?(?:;|(?=\s*\{))/i,
		inside: {
			'rule': /@[\w-]+/
			// See rest below
		}
	},
	'url': /url\((?:(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1|.*?)\)/i,
	'selector': /[^{}\s][^{};]*?(?=\s*\{)/,
	'string': {
		pattern: /("|')(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,
		greedy: true
	},
	'property': /[-_a-z\xA0-\uFFFF][-\w\xA0-\uFFFF]*(?=\s*:)/i,
	'important': /\B!important\b/i,
	'function': /[-a-z0-9]+(?=\()/i,
	'punctuation': /[(){};:]/
};
```

If so, just load your custom language and pass the `language` prop.

```js
<Prism language="css" code={ myCssCode } />
```

**Comment by egoist** [comment]
Yeah, you can also simply require what you need: https://unpkg.com/prismjs@1.9.0/components/
